### ISSUE TITLE
Test .py file for pre-trained weight

### ISSUE THREAD

**Issue by Wspiron** [xheon/JointEmbedding#6]
hello,thanks for your excellent work, i got some trouble to apply the pre-trained weight you given, but the file got bug(pre-trained weight have dismatched dimension).
Can you provide the test.py which is suitable for the pre-trained weight? Thanks a lot.

**Comment by Wspiron** [comment]
I modified the some files in project slightly and got the results, thanks a lot.

**Comment by florianlanger** [comment]
I am also encountering the same problem. @Wspiron Is it possible for you to post the modifications you made that fixed it? Thanks!
